Repository kokonior/Java-Projects, pull requests merged in 2021-10, with the labels that each got.

#1 agunglaksonop #main source
  agunglaksonop-BangunDatar.java
Labels: hacktoberfest-accepted

#2 added new java
  mbul48AngkaRibuan.java
Labels: enhancement, hacktoberfest-accepted

#5 Update README.md
  README.md
Labels: enhancement, hacktoberfest-accepted

#4 Learn Polimorfisme
  Polimorfisme-ayam.java
  Polimorfisme-hewan.java
  Polimorfisme-kucing.java
  Polimorfisme-main.java
Labels: enhancement, hacktoberfest-accepted

#7 Create GridLayoutPane.java
  GridLayoutPane.java
Labels: hacktoberfest-accepted, Create

#6 Learn Inheritance + GUI.
  Latihan_Inheritance1.java
  Latihan_Inheritance2.java
  Latihan_Inheritance3.java
  Latihan_Inheritance_GUI.java
Labels: enhancement, hacktoberfest-accepted

#9 Create Motorcycle.java
  Motorcycle.java
Labels: hacktoberfest-accepted, Create

#10 Patch 1
  garlek123.java
Labels: enhancement, hacktoberfest-accepted

#13 Create Encapsulation.java
  Encapsulation.java
Labels: hacktoberfest-accepted, Create

#17 binarytodecimalconverter_Debdeep Banerjee
  binarytodecimal_converter.java
Labels: enhancement, hacktoberfest-accepted

#16 Create Operator
  Operator
Labels: hacktoberfest-accepted, Create

#15 Create ListApp.java
  ListApp.java
Labels: hacktoberfest-accepted, Create

#14 Create ArrayApp.java
  ArrayApp.java
Labels: hacktoberfest-accepted, Create

#18 Create BinSearchAscending.java
  BinSearchAscending.java
Labels: hacktoberfest-accepted, Create

#19 Translated In English with Some Modification
  calculator.java
Labels: enhancement, hacktoberfest-accepted
